name: Prod Deploy

on:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: golang:1.23.4-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: go test ./tests/...

  deploy:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to server
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S bash -c '
            cd ${{ secrets.PROJECT_PATH }}
            make deploy
            '
          EOF
        env:
          SSHPASS: ${{ secrets.SSH_PASSWORD }}

      - name: Cleanup
        run: unset SSHPASS
