name: Prod Deploy

on:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: golang:1.23.4-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Настройка Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run tests
        run: make test  # Запуск тестов