name: Prod Deploy

on:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: golang:1.20-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: make test  # Запуск тестов