name: Prod Deploy

on:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: golang:1.23.4-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: go test ./tests/...